# Generated by Django 3.1.13 on 2022-01-05 07:19
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("puzzle_editing", "0004_auto_20210919_2138"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="meta_writers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who are writing the metas for the round",
                related_name="writing_rounds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
